#!/usr/bin/env python3
import pathlib
import re

CHIP_CLUSTERS_DIR = pathlib.Path('/workspaces/matterproxy/connectedhomeip/zzz_generated/app-common/clusters')
OUT_FILE = pathlib.Path('/workspaces/matterproxy/matter-dissector_ws4.6.3/im_name_tables.inc')

CLUSTER_ID_RE = re.compile(r"inline\s+constexpr\s+ClusterId\s+Id\s*=\s*(0x[0-9A-Fa-f]+)\s*;")
ITEM_RE_TEMPLATE = r"namespace\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{{\s*inline\s+constexpr\s+{kind}\s+Id\s*=\s*(0x[0-9A-Fa-f]+)\s*;"

ATTR_RE = re.compile(ITEM_RE_TEMPLATE.format(kind='AttributeId'), re.MULTILINE)
CMD_RE = re.compile(ITEM_RE_TEMPLATE.format(kind='CommandId'), re.MULTILINE)
EVT_RE = re.compile(ITEM_RE_TEMPLATE.format(kind='EventId'), re.MULTILINE)


def parse_cluster(cluster_dir: pathlib.Path):
    cluster_id_h = cluster_dir / 'ClusterId.h'
    m = CLUSTER_ID_RE.search(cluster_id_h.read_text(encoding='utf-8', errors='ignore'))
    if not m:
        return None

    cluster_id = int(m.group(1), 16)
    cluster_name = cluster_dir.name

    attrs = []
    cmds = []
    evts = []

    attr_h = cluster_dir / 'AttributeIds.h'
    if attr_h.exists():
        text = attr_h.read_text(encoding='utf-8', errors='ignore')
        for name, hexid in ATTR_RE.findall(text):
            attrs.append((int(hexid, 16), name))

    cmd_h = cluster_dir / 'CommandIds.h'
    if cmd_h.exists():
        text = cmd_h.read_text(encoding='utf-8', errors='ignore')
        for name, hexid in CMD_RE.findall(text):
            cmds.append((int(hexid, 16), name))

    evt_h = cluster_dir / 'EventIds.h'
    if evt_h.exists():
        text = evt_h.read_text(encoding='utf-8', errors='ignore')
        for name, hexid in EVT_RE.findall(text):
            evts.append((int(hexid, 16), name))

    return {
        'id': cluster_id,
        'name': cluster_name,
        'attrs': sorted(set(attrs)),
        'cmds': sorted(set(cmds)),
        'evts': sorted(set(evts)),
    }


def emit():
    clusters = []
    for p in sorted(CHIP_CLUSTERS_DIR.iterdir()):
        if not p.is_dir():
            continue
        try:
            info = parse_cluster(p)
        except Exception:
            continue
        if info is not None:
            clusters.append(info)

    clusters.sort(key=lambda x: x['id'])

    lines = []
    lines.append('// Auto-generated by tools/gen_im_name_tables.py from connectedhomeip v1.5 branch')
    lines.append('// Do not edit manually.')
    lines.append('')

    lines.append('static const ClusterNameEntry kClusterNameTable[] = {')
    for c in clusters:
        lines.append(f'    {{ 0x{c["id"]:08X}, "{c["name"]}" }},')
    lines.append('};')
    lines.append('')

    lines.append('static const ScopedNameEntry kAttributeNameTable[] = {')
    for c in clusters:
        for aid, aname in c['attrs']:
            lines.append(f'    {{ 0x{c["id"]:08X}, 0x{aid:08X}, "{aname}" }},')
    lines.append('};')
    lines.append('')

    lines.append('static const ScopedNameEntry kCommandNameTable[] = {')
    for c in clusters:
        for cid, cname in c['cmds']:
            lines.append(f'    {{ 0x{c["id"]:08X}, 0x{cid:08X}, "{cname}" }},')
    lines.append('};')
    lines.append('')

    lines.append('static const ScopedNameEntry kEventNameTable[] = {')
    for c in clusters:
        for eid, ename in c['evts']:
            lines.append(f'    {{ 0x{c["id"]:08X}, 0x{eid:08X}, "{ename}" }},')
    lines.append('};')
    lines.append('')

    OUT_FILE.write_text('\n'.join(lines), encoding='utf-8')


if __name__ == '__main__':
    emit()
